server:
  port: 8102

spring:
  datasource:
    url: jdbc:postgresql://34.214.181.53/telegram
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
