server:
  port: 8200

spring:
  datasource:
    url: jdbc:h2:file:./fltelegram;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

telegram:
  botName: FreelanceNotificationsBot
  botToken: 552373266:AAFR567O55SZs8pco7mk6i6us_YLJasO7IA
