#TODO move to config server
spring:
  datasource:
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL93Dialect
---
spring:
  profiles: app1
server:
  port: 8017
spring:
  datasource:
    url: jdbc:postgresql://81.177.160.138/flproject
---
spring:
  profiles: app2
server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://81.177.160.138/ilya